acl:
# набор правил
  - type:     suffix
    value:    count
    method:   sum
    divider:  '.'

  - type:     suffix
    value:    size
    method:   avg
    divider:  '.'

  - type:     suffix
    value:    max
    method:   max
    divider:  '.'

  - type:     suffix
    value:    min
    method:   min
    divider:  '.'


  - type:     default
    method:   avg

network:
  listen:
    # где слушаем
    host: 0.0.0.0
    port: 2004

  parent:
      # подключение родителя
      host: 127.0.0.1
      port: 2003
      # с каким лагом слать
      lag: 5
  
log:
  facility: 'local7'
