#!/usr/bin/perl

use warnings;
use strict;

use utf8;
use open qw(:std :utf8);

use lib qw(lib);
use DR::Statsd::Proxy::Debug;
use DR::Statsd::Proxy;
use URI;
use Coro;

DEBUGF 'Statsd proxy running';

my $server = new DR::Statsd::Proxy
    parent      => URI->new('udp://gr.rmfr.ru:2003'),
    bind_host   => '0.0.0.0',
    bind_port   => 2004,
    lag         => 10,
;


$server->start;

my $coro = $Coro::current;

local $SIG{INT} = sub { $coro->ready if $coro };
local $SIG{TERM} = sub { $coro->ready if $coro };

Coro::schedule;


DEBUGF 'Stopping server';

$server->stop;
